# Ruff配置文件
# 详细配置说明：https://docs.astral.sh/ruff/

[tool.ruff]
# 启用更多规则集
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
    "RUF", # ruff-specific rules
    "N",   # pep8-naming
    "D",   # pydocstyle
    "S",   # flake8-bandit (security)
    "T20", # flake8-print
    "PT",  # flake8-pytest-style
]

# 忽略特定规则
ignore = [
    "D100", # Missing docstring in public module
    "D104", # Missing docstring in public package
    "S101", # Use of assert detected (pytest uses assert)
    "T20",  # Avoid print statements (允许在示例中使用)
]

# 行长度限制（与项目规范一致）
line-length = 88

# 目标Python版本
target-version = "py36"

# 排除目录
exclude = [
    ".git",
    "__pycache__",
    ".venv",
    ".uv",
    "build",
    "dist",
    "docs/_build",
    "htmlcov",
    ".tox",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
]

# 每个文件的最大修复数
fix = true
show-fixes = true

[tool.ruff.pydocstyle]
# 使用Google风格的docstring
convention = "google"

[tool.ruff.isort]
# 导入排序配置
known-first-party = ["pyutils"]
force-single-line = false
lines-after-imports = 2
split-on-trailing-comma = true

[tool.ruff.flake8-pytest-style]
# pytest风格配置
fixture-parentheses = false
parametrize-names-type = "tuple"
parametrize-values-type = "tuple"
parametrize-values-row-type = "tuple"

[tool.ruff.per-file-ignores]
# 测试文件特殊规则
"tests/**/*.py" = [
    "D",    # 测试文件不需要docstring
    "S101", # 测试中允许assert
    "T20",  # 测试中允许print
]
# 示例文件特殊规则
"examples.py" = [
    "T20",  # 示例中允许print
    "D",    # 示例不需要完整docstring
]
"benchmark.py" = [
    "T20",  # 基准测试中允许print
]